README.md
cli.md
hardware-api.md

Merge whenever; I'll keep adding stuff

Getting this repo going

---

cli.md

Update cli.md for npm install

---

hardware-api.md

Fixes #15 
I think I was fairly thorough with documenting all the public methods of the `tessel.led` object and each method exposed to each `led`.

Adds LED api to hardware-api.md

---

cli.md

adds 'ap' command docs

---

cli.md

Clarifying NodeJS requirement based on errors and issue here: https://github.com/tessel/t2-cli/issues/470

Clarify NodeJS requirement

---

cli.md

adds .tesselignore & .tesselinclude docs to cli docs

---

hardware-api.md

Dependent on https://github.com/tessel/t2-firmware/pull/155.

Adds documentation for PWM

---

cli.md

and a little more
@johnnyman727 r?

fixes https://github.com/tessel/t2-docs/issues/47

---

tutorials/diy-module.md

Not sure if this is the right way to link but these links are broken on the site.

Fix broken links

---

hardware-api.md
network-api.md

Adds Network API

---

hardware-api.md

Presently, I see this: 
But I'm not at all sure why, because it looks like it's correct in the source without these changes. 
Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

Attempting to fix PWM column/row

---

cli.md

Fixed.
Fixes #76 (edit by HipsterBrown to auto-close issue 75)

Fixes #75; t2 ap --on/--off.

---

GLOSSARY.md
SUMMARY.md
book.json

Excited to try the gitbooks glossary feature on our new docs @HipsterBrown what do you think of this as a first pass?
(And: any edits welcome)

adds first pass at an initial glossary

---

API/CLI.md

Have not tried these option but logically correct.

Swap "on" and "off"

---

Tutorials/Communication_Protocols.md

Fixing a broken link on the Communication Protocols tutorial.

Fix broken link

---

README.md

add code of conduct badge to docs repo

---

API/Languages.md
API/Supported_Languages.md
SUMMARY.md

Used to be like
Now more like
r? @rwaldron

expanded supported languages

---

API/CLI.md

Change `http://tessel.io/t2-cli ` to `http://tessel.io/t2-start` in CLI readme

Update start experience link

---

API/Hardware_API.md
SUMMARY.md
Tutorials/PWM.md

Fixes https://github.com/tessel/t2-docs/issues/84

refactors PWM docs with Fritzing, method definitions

---

API/Modules.md

Fix modules page link in `API/Modules`

update link to modules page

---

API/Modules.md

fixes https://github.com/tessel/t2-docs/issues/114

---

API/CLI.md

Added t2 reboot to Tessel Management section.  Updated punctuation and descriptions of other commands in the Management section to match.

add t2 reboot to Tessel Management section of CLI.md closes #123

---

API/Hardware_API.md

fixes https://github.com/tessel/t2-docs/issues/132

---

API/Hardware_API.md

fixes https://github.com/tessel/t2-docs/issues/133

---

API/Hardware_API.md
GLOSSARY.md
SUMMARY.md

added more explanation to I2C transfer command

---

API/Supported_Languages.md

fixes https://github.com/tessel/t2-docs/issues/131

---

API/Hardware_API.md

@michelchrome and @johnnyman727 can you please review?

fixes https://github.com/tessel/t2-docs/issues/139

---

Debugging/LAN_Discovery.md

Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

Debugging/LAN_Discovery.md: revise "An issue with network configuration" prose

---

Hardware/Modules.md

Added the links of Hardware information for the different modules in modules.md  file.(fixes #145)

Fixes #145 - Added the Hardware Info links

---

Tutorials/Communication_Protocols.md

Signed-off-by: Rick Waldron <waldron.rick@gmail.com>

Code update for Node.js 6 capabilities: Tutorials/Communication_Protocols.md

---

API/Supported_Languages.md

fix link to packages.tessel.io

---

API/Hardware_API.md

Fix #174. Link for the image added below it.

Issue - 174

---

API/Hardware_API.md

This change extends the Hardware API documentation with short description and example for pin.toggle().
@HipsterBrown Please review.

Fixes #178

---

Debugging/LAN_Discovery.md

Signed-off-by: Wilhelm Erasmus <wilhelm.erasmus@burtronix.com>

Added DNS-SD notes for Linux

---

API/Supported_Languages.md

Edited a sentence from 'There is support for binary modules on Tessel 2 that are precompiled', to 'There is support for precompiled binary modules on Tessel 2.'

Edited a sentence

---

API/Hardware_API.md

Team DelSquared (RGSoC '18): Changed variable names
